[package]
name = "guest_bench"
version = "0.1.0"
edition = "2021"

[workspace]

[profile.release]
opt-level = 0

[dependencies]
risc0-zkvm = { version = "1.2.0", default-features = false, features = ['std'] }
nalgebra = "0.33.2"
